"""Backend-neutral AMAT targeting layer."""
from .lambert import LambertSolution, default_lambert_tof_s, hohmann_transfer_time_s, solve_lambert
from .patched_conics import (
    ArrivalHyperbola,
    CircularOrbitState,
    PatchedConicsCandidate,
    PatchedConicsSoiCandidate,
    arrival_hyperbola_from_vinf,
    laplace_soi_radius_km,
    solve_circular_coplanar_patched_conics,
    solve_circular_coplanar_soi_patched_conics,
)
from .patched_conics_correction import (
    BodyState,
    CircularInsertionBurn,
    EncounterTarget,
    FinalOrbitTarget,
    RelativeState,
    SpacecraftState,
    assess_encounter,
    assess_final_orbit,
    circular_insertion_burn,
    osculating_orbit,
)
from .cislunar import (
    BodyEphemerisSample,
    CislunarLambertSeed,
    ConicChainLeg,
    ConicChainNode,
    ConicChainSeed,
    EphemerisLambertSeed,
    load_gmat_body_ephemeris_csv,
    retarget_cislunar_mission_spec,
    solve_conic_chain_seed,
    solve_ephemeris_lambert_seed,
    solve_single_leg_ephemeris_lambert_seed,
)
from .closed_loop import (
    StmClosedLoopIteration,
    StmClosedLoopResult,
    StmTargetStateAssessment,
    build_stm_target_state_assessment,
    close_with_stm,
    execute_patched_conics_stm_closed_loop,
)
from .stm_correction import StmCorrectionResult, solve_stm_target_state_correction
from .targeting_policy import TargetingPolicyResult, execute_targeting_policy
from .evaluation import build_acceptance_result, evaluate_simulation
from .service import solve_file, validate_file, canonicalize_file
__all__ = [
    "LambertSolution",
    "default_lambert_tof_s",
    "hohmann_transfer_time_s",
    "solve_lambert",
    "ArrivalHyperbola",
    "CircularOrbitState",
    "PatchedConicsCandidate",
    "PatchedConicsSoiCandidate",
    "arrival_hyperbola_from_vinf",
    "laplace_soi_radius_km",
    "solve_circular_coplanar_patched_conics",
    "solve_circular_coplanar_soi_patched_conics",
    "BodyState",
    "CircularInsertionBurn",
    "EncounterTarget",
    "FinalOrbitTarget",
    "RelativeState",
    "SpacecraftState",
    "assess_encounter",
    "assess_final_orbit",
    "circular_insertion_burn",
    "osculating_orbit",
    "StmCorrectionResult",
    "solve_stm_target_state_correction",
    "TargetingPolicyResult",
    "execute_targeting_policy",
    "build_acceptance_result",
    "evaluate_simulation",
    "solve_file",
    "validate_file",
    "canonicalize_file",
    "BodyEphemerisSample",
    "CislunarLambertSeed",
    "ConicChainLeg",
    "ConicChainNode",
    "ConicChainSeed",
    "EphemerisLambertSeed",
    "load_gmat_body_ephemeris_csv",
    "retarget_cislunar_mission_spec",
    "solve_conic_chain_seed",
    "solve_ephemeris_lambert_seed",
    "solve_single_leg_ephemeris_lambert_seed",
    "StmClosedLoopIteration",
    "StmClosedLoopResult",
    "StmTargetStateAssessment",
    "build_stm_target_state_assessment",
    "close_with_stm",
    "execute_patched_conics_stm_closed_loop",
]
